name: destination_lock
description: Lock/unlock destinations that your application can reach
version: 0.0.2+2
homepage: https://github.com/sunderee/Destination-Lock/blob/master/README.md
repository: https://github.com/sunderee/Destination-Lock

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
